package com.ae_osteo.entity;
// Generated 15 mai 2018 19:22:19 by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "ae_osteo")
public class Facture implements java.io.Serializable {

	private Integer idFacture;
	private Consultation consultation;
	private Patient patient;
	private Reglement reglement;

	public Facture() {
	}

	public Facture(Consultation consultation, Patient patient, Reglement reglement) {
		this.consultation = consultation;
		this.patient = patient;
		this.reglement = reglement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_facture", unique = true, nullable = false)
	public Integer getIdFacture() {
		return this.idFacture;
	}

	public void setIdFacture(Integer idFacture) {
		this.idFacture = idFacture;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rf_id_consultation", nullable = false)
	public Consultation getConsultation() {
		return this.consultation;
	}

	public void setConsultation(Consultation consultation) {
		this.consultation = consultation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rf_id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rf_id_reglement", nullable = false)
	public Reglement getReglement() {
		return this.reglement;
	}

	public void setReglement(Reglement reglement) {
		this.reglement = reglement;
	}

}
