package com.ae_osteo.entity;
// Generated 15 mai 2018 19:22:19 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", catalog = "ae_osteo")
public class Patient implements java.io.Serializable {

	private Integer idPatient;
	private StatutMarital statutMarital;
	private String nom;
	private String prenom;
	private Date dateNaissance;
	private Integer telephone;
	private String adresse1;
	private String adresse2;
	private String adresse3;
	private Integer codePostal;
	private String ville;
	private String recoPar;
	private String medecin;
	private String profession;
	private String habitus;
	private String observations;
	private Set<Facture> factures = new HashSet<Facture>(0);
	private Set<Antecedents> antecedentses = new HashSet<Antecedents>(0);
	private Set<Rdv> rdvs = new HashSet<Rdv>(0);

	public Patient() {
	}

	public Patient(StatutMarital statutMarital, String nom, String prenom) {
		this.statutMarital = statutMarital;
		this.nom = nom;
		this.prenom = prenom;
	}

	public Patient(StatutMarital statutMarital, String nom, String prenom, Date dateNaissance, Integer telephone,
			String adresse1, String adresse2, String adresse3, Integer codePostal, String ville, String recoPar,
			String medecin, String profession, String habitus, String observations, Set<Facture> factures,
			Set<Antecedents> antecedentses, Set<Rdv> rdvs) {
		this.statutMarital = statutMarital;
		this.nom = nom;
		this.prenom = prenom;
		this.dateNaissance = dateNaissance;
		this.telephone = telephone;
		this.adresse1 = adresse1;
		this.adresse2 = adresse2;
		this.adresse3 = adresse3;
		this.codePostal = codePostal;
		this.ville = ville;
		this.recoPar = recoPar;
		this.medecin = medecin;
		this.profession = profession;
		this.habitus = habitus;
		this.observations = observations;
		this.factures = factures;
		this.antecedentses = antecedentses;
		this.rdvs = rdvs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_patient", unique = true, nullable = false)
	public Integer getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(Integer idPatient) {
		this.idPatient = idPatient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rf_id_statut_marital", nullable = false)
	public StatutMarital getStatutMarital() {
		return this.statutMarital;
	}

	public void setStatutMarital(StatutMarital statutMarital) {
		this.statutMarital = statutMarital;
	}

	@Column(name = "nom", nullable = false, length = 150)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 150)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_naissance", length = 19)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@Column(name = "telephone")
	public Integer getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Integer telephone) {
		this.telephone = telephone;
	}

	@Column(name = "adresse 1", length = 150)
	public String getAdresse1() {
		return this.adresse1;
	}

	public void setAdresse1(String adresse1) {
		this.adresse1 = adresse1;
	}

	@Column(name = "adresse2", length = 150)
	public String getAdresse2() {
		return this.adresse2;
	}

	public void setAdresse2(String adresse2) {
		this.adresse2 = adresse2;
	}

	@Column(name = "adresse3", length = 150)
	public String getAdresse3() {
		return this.adresse3;
	}

	public void setAdresse3(String adresse3) {
		this.adresse3 = adresse3;
	}

	@Column(name = "code postal")
	public Integer getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(Integer codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "ville", length = 150)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "reco_par", length = 300)
	public String getRecoPar() {
		return this.recoPar;
	}

	public void setRecoPar(String recoPar) {
		this.recoPar = recoPar;
	}

	@Column(name = "medecin", length = 300)
	public String getMedecin() {
		return this.medecin;
	}

	public void setMedecin(String medecin) {
		this.medecin = medecin;
	}

	@Column(name = "profession", length = 150)
	public String getProfession() {
		return this.profession;
	}

	public void setProfession(String profession) {
		this.profession = profession;
	}

	@Column(name = "habitus")
	public String getHabitus() {
		return this.habitus;
	}

	public void setHabitus(String habitus) {
		this.habitus = habitus;
	}

	@Column(name = "observations")
	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Antecedents> getAntecedentses() {
		return this.antecedentses;
	}

	public void setAntecedentses(Set<Antecedents> antecedentses) {
		this.antecedentses = antecedentses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "patient")
	public Set<Rdv> getRdvs() {
		return this.rdvs;
	}

	public void setRdvs(Set<Rdv> rdvs) {
		this.rdvs = rdvs;
	}

}
