package com.ae_osteo.entity;
// Generated 15 mai 2018 19:22:19 by Hibernate Tools 5.1.7.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rdv generated by hbm2java
 */
@Entity
@Table(name = "rdv", catalog = "ae_osteo")
public class Rdv implements java.io.Serializable {

	private Integer idRdv;
	private Consultation consultation;
	private Patient patient;
	private Date dateRdv;
	private Date dateProchainRdv;

	public Rdv() {
	}

	public Rdv(Consultation consultation, Patient patient) {
		this.consultation = consultation;
		this.patient = patient;
	}

	public Rdv(Consultation consultation, Patient patient, Date dateRdv, Date dateProchainRdv) {
		this.consultation = consultation;
		this.patient = patient;
		this.dateRdv = dateRdv;
		this.dateProchainRdv = dateProchainRdv;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_rdv", unique = true, nullable = false)
	public Integer getIdRdv() {
		return this.idRdv;
	}

	public void setIdRdv(Integer idRdv) {
		this.idRdv = idRdv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rf_id_consultation", nullable = false)
	public Consultation getConsultation() {
		return this.consultation;
	}

	public void setConsultation(Consultation consultation) {
		this.consultation = consultation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rf_id_patient", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_rdv", length = 19)
	public Date getDateRdv() {
		return this.dateRdv;
	}

	public void setDateRdv(Date dateRdv) {
		this.dateRdv = dateRdv;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_prochain_rdv", length = 19)
	public Date getDateProchainRdv() {
		return this.dateProchainRdv;
	}

	public void setDateProchainRdv(Date dateProchainRdv) {
		this.dateProchainRdv = dateProchainRdv;
	}

}
