package com.ae_osteo.entity;
// Generated 15 mai 2018 19:22:19 by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StatutMarital generated by hbm2java
 */
@Entity
@Table(name = "statut_marital", catalog = "ae_osteo", uniqueConstraints = @UniqueConstraint(columnNames = "code_statut_marital"))
public class StatutMarital implements java.io.Serializable {

	private Integer idStatutMarital;
	private String codeStatutMarital;
	private String libelleStatutMarital;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public StatutMarital() {
	}

	public StatutMarital(String codeStatutMarital, String libelleStatutMarital) {
		this.codeStatutMarital = codeStatutMarital;
		this.libelleStatutMarital = libelleStatutMarital;
	}

	public StatutMarital(String codeStatutMarital, String libelleStatutMarital, Set<Patient> patients) {
		this.codeStatutMarital = codeStatutMarital;
		this.libelleStatutMarital = libelleStatutMarital;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_statut_marital", unique = true, nullable = false)
	public Integer getIdStatutMarital() {
		return this.idStatutMarital;
	}

	public void setIdStatutMarital(Integer idStatutMarital) {
		this.idStatutMarital = idStatutMarital;
	}

	@Column(name = "code_statut_marital", unique = true, nullable = false, length = 45)
	public String getCodeStatutMarital() {
		return this.codeStatutMarital;
	}

	public void setCodeStatutMarital(String codeStatutMarital) {
		this.codeStatutMarital = codeStatutMarital;
	}

	@Column(name = "libelle_statut_marital", nullable = false, length = 45)
	public String getLibelleStatutMarital() {
		return this.libelleStatutMarital;
	}

	public void setLibelleStatutMarital(String libelleStatutMarital) {
		this.libelleStatutMarital = libelleStatutMarital;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statutMarital")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
